### ISSUE TITLE
Demo failed to run.

### ISSUE THREAD

**Issue by GYDmedwin** [checkpoint-restore/criu-coordinator#1]
Hi,
 I tried to run the demo(c1,c2,c3) in the test directory, but it failed.

> INFO - [==] New client connected: 127.0.0.1:46872
> INFO - [>>] Receive client ID, action and dependencies
> INFO - [c1] [>>] ID: c1
> INFO - [c1] [>>] ACTION: pre-dump
> INFO - [c1] [>>] DEPENDENCIES: c2
> INFO - [c1] [==] Insert client ID
> INFO - [c1] [==] Wait for all dependencies to connect
> INFO - [c1] [==] Checking connection of: c2
> INFO - [==] New client connected: 127.0.0.1:46882
> INFO - [>>] Receive client ID, action and dependencies
> INFO - [c2] [>>] ID: c2
> INFO - [c2] [>>] ACTION: pre-dump
> INFO - [c2] [>>] DEPENDENCIES: c2
> ERROR - Timeout for connection of c2
> INFO - [c1] [==] Timeout for dependency: c2
> INFO - [c1] [<<] Sending Timeout
> INFO - [c1] [==] Client disconnected
> INFO - [c2] [==] Insert client ID
> INFO - [c2] [==] Wait for all dependencies to connect
> INFO - [c2] [==] Checking connection of: c2
> INFO - [c2] [==] c2 connected
> INFO - [c2] [==] Client is ready
> INFO - [c2] [==] Wait for all dependencies to be ready
> INFO - [c2] [==] Checking readiness of: c2
> INFO - [c2] [==] Dependency c2 is ready
> INFO - [c2] [<<] Sending ACK
> INFO - [c2] [==] Client disconnected
> INFO - [==] New client connected: 127.0.0.1:56974
> INFO - [>>] Receive client ID, action and dependencies
> INFO - [c2] [>>] ID: c2
> INFO - [c2] [>>] ACTION: post-dump
> INFO - [c2] [>>] DEPENDENCIES: c2
> INFO - [c2] [==] Wait for all dependencies to create local checkpoint
> INFO - [c2] [==] Checking local checkpoint: c2
> INFO - [c2] [<<] Sending ACK
> INFO - [c2] [==] Client disconnected
> INFO - [c2] [==] Client removed

After the \test directory example failed to run, I just used c1 and c2 in the directory and created the corresponding /tmp/test/c1 and /tmp/test/c2. At the same time, I modified the configuration file to make c1 dependent on c2, and c2 dependent on itself. However, from the above log, the criu-coordinator server did not recognize c2 the first time, but regarded it as a new connection.

I am not sure if my operation is wrong, and hope to get your reply. Thanks!

Environment ：
> CRIU  v4.0

criu-coordinator.json:
>{
        "id": "c1",
        "dependencies":"c2",
        "address": "127.0.0.1",
        "port": "8080",
        "log-file": "coordinator.log"
}

> {
        "id": "c2",
        "dependencies":"c2",
        "address": "127.0.0.1",
        "port": "8080",
        "log-file": "coordinator.log"
}

steps:
> criu-coordinator server --address 127.0.0.1 --port 8080

> criu dump -t ‘pidof c1’ -D /tmp/test/c1 -j -v4 && echo OK
> criu dump -t 'pidof c2' -D /tmp/test/c1 -j -v4 && echo OK

**Comment by rst0git** [comment]
@GYDmedwin Thank you for reaching out! This project is still under development and is part of my PhD research [^1][^2][^3].

[^1]: https://lpc.events/event/18/contributions/1803/
[^2]: https://kccnceu2024.sched.com/event/1YeT4
[^3]: https://research.redhat.com/events/europe-rig-april-2023/

Please feel free to get in touch via email or the Kubernetes slack if you are interested in collaborating with us!
